### ISSUE TITLE
请求的 json 直接使用 GitHub Raw

### ISSUE THREAD

**Issue by ccloli** [FirefoxBar/firefoxbar.github.io#4]
上一个 [commit](https://github.com/FirefoxBar/firefoxbar.github.io/commit/4628ed9fc5d244c5bbc6827a2e1d26def565375b) 的内容是“SAE 钩子不更新，尝试去掉”，所以现在 SAE 返回的数据是不更新了么？

刚刚推送了新的脚本并修改了 `userscripts.json`，但是 SAE 返回的数据没有更新。

测试了一下，`raw.githubusercontent.com` 返回的 headers 里有 `Access-Control-Allow-Origin:*`，所以是可以跨域的。

所以需要将所有请求 json 的 ajax 都换成 `raw.githubusercontent.com` 的地址么？

**Comment by linusyu** [comment]
一开始是用 raw 的。shuangya 说被墙了。就搞了个 sae.

**Comment by sylingd** [comment]
随意
我是考虑到raw在某些地区响应非常慢
如果你们觉得没有必要，也可以改回去

**Comment by ccloli** [comment]
或者可以试试 [RawGit](https://rawgit.com/)？

**Comment by iMyon** [comment]
其实可以把master分支删了，直接用gh-pages

**Comment by linusyu** [comment]
去掉 SAE，降低复杂性，减少不可控因素。
